selection_method: spectrclust # Options: random, broadcast, heatkernel, spectrclust
selection_ratio: 0.5 # Ratio of neighbors selected
dist: cosine # Options: eucl, cosine 
num_eig: 3 # Numeber of eigenvalues to consider (<= num_clients)
t: 40 # Diffusion time, small = local, large = global
tau: 1 # Temperature for client selection