architecture: mnistCNN # NOTE: Not used for now
lr: 0.01
epochs: 5
optimizer: SGD  # Options: SGD, Adam
rho: 0.1 # mixing parameter for model update
selection_ratio: 0.5 # Ratio of neighbors selected

selection_method: spectrclust # Options: random, broadcast, heatkernel, spectrclust
dist: cosine # Options: eucl, cosine 
num_eig: 3 # Numeber of eigenvalues to consider (<= num_clients)
t: 40 # Diffusion time, small = local, large = global
tau: 1 # Temperature for client selection