num_clients: 8
topology: small # Options: ring, random, fullycon, star, smallwrld, grid, women, karate, floorent
edge_proba: 0.4 # For random topology
k: 4 # for smallwrld topology
p: 0.3 # for smallwrld topology