# Default configuration for decentralized federated learning simulation
defaults:
  - federation: base
  - dataset: mnist_iid
  - network: random10
  - client: random

seed: 42

hydra:
  run:
    dir: .        
  job:
    chdir: false   