# Default configuration for decentralized federated learning simulation
epochs: 5
rounds: 50
rounds_patience: 5


dataset:
  name: mnist  # Options: mnist, cifar10
  partition: dirichlet  # Options: iid, dirichlet
  batch_size: 64
  alpha: 0.3 # For dirichlet

# Topology
network:
  num_clients: 10
  topology: random # Options: ring, random, fullycon, star, smallwrld, grid, women, karate, floorent
  edge_proba: 0.4 # For random topology
  k: 4 # for random topology
  p: 0.3 # for random topology

client:
  lr: 0.01
  optimizer: SGD  # Options: SGD, Adam
  rho: 0.1 # mixing parameter for model update

  selection_method: heatkernel # Options: random, broadcast, heatkernel, spectrclust
  selection_ratio: 0.5 # Ratio of neighbors selected
  dist: eucl # Options: eucl, cos 
  num_eig: 3 # Numeber of eigenvalues to consider (<= num_clients)
  t: 40 # Diffusion time, small = local, large = global

# Hydra configuration for the project. DO NOT TOUCH!
hydra:
  run:
    dir: .        
  job:
    chdir: false   